config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :books
  root "books#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
    belongs_to :user
    belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :books
end

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :book
    belongs_to :user    
end
  

app/models/user.rb
class User < ApplicationRecord
  has_many :books
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
     before_action :find_book, only: [:show, :edit, :update, :destroy]


    def index
        @books = Book.all.order("created_at DESC")
    end


    def show
    end
    
    def new
        @book = current_user.books.build
        @category = Category.all.map { |c| [c.name, c.id] }
    end

    def create
        @book = current_user.books.build(book_params)

        if @book.save
           redirect_to root_path
        else
            render 'new'
        end
    end

    def edit
    end

    def update
        if @book.update(book_params)
            redirect_to book_path(@book)
        else
            render 'edit'
        end
    end

    def destroy
        @book.destroy
        redirect_to root_path
    end

    private

    def book_params
        params.require(:book).permit(:title, :description, :author)
    end
    
    def find_book
        @book = Book.find(params[:id])
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_helper.rb
module BookHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= simple_form_for @book do |f| %>
    <%= select_tag(:category_id,options_for_select(@categories), :prompt=>"select a category")%>
    <%= f.input :title, label: "Book title" %>
    <%= f.input :description %>
    <%= f.input :author %>
    <%= f.button :submit %>
<% end %>

app/views/books/edit.html.erb
<h1> Edit Book </h1>

<%= render 'form' %>

app/views/books/index.html.erb
<% @books.each do |book| %>
  <h2><%= link_to book.title, book_path(book) %></h2>
<% end %>

app/views/books/new.html.erb
<h1>New Book Created</h1>

<%= render 'form' %>

app/views/books/show.html.erb
<h2><%=  @book.title %></h2>
<h3><%= @book.author %></h3>
<p><%= @book.description %></p>

<%= link_to "Back", root_path %>

   <% if user_signed_in? %>

     <% if @book.user_id = current_user.id %>
        <%= link_to "Edit", edit_book_path(@book) %>
        <%= link_to "Delete", book_path(@book), method: :delete, data: { confirm: "Are You Sure?" }  %>
     <% end %>
  <% end %> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookStore</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!-- CSS only -->
    <!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

      <nav class="navbar navbar-expand-lg bg-light">
        <div class="container">
          <div class="navbar-header">
             <%= link_to "Book Review", root_path, class: "navbar-brand" %>
          </div>
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item me-auto">
                <%= link_to "Sign Up", new_user_registration_path %>
              </li>
              <li class="nav-item me-auto">
                    <% if user_signed_in? %>
                      <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
                    <% else %>
                       <li><%= link_to "Log In",  new_user_session_path %></li>
                    <% end %>
              </li>  
          </ul>
          <ul class="nav navbar-nav">
             <% if user_signed_in? %>
                <li><%= link_to "Add Book", new_book_path %></li>
             <% end %>
             
          </ul>
       </div>
      </nav>
    

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    
    <%= yield %>
    <!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
</html>